### ISSUE TITLE
Add Pull Request checklist

### ISSUE THREAD

**Issue by Ben-PH** [Ben-PH/shader_brot#9]
- [ ] Changes don't clash with readme
- [ ] Changes avoid README bloat (eg requiring a readme explanation such as ui explanation where in-process is where it should be)
- [ ] Passes build tests
  - [ ] for user-tests, request includes an appropriately detailed description
- [ ] Passes auto-tests
